export {default as logo1} from './logo1.svg';
export {default as logo2} from './logo2.svg';
export {default as logo3} from './logo3.svg';
export {default as logo4} from './logo4.svg';
export {default as logo5} from './logo5.svg';
export {default as logo6} from './logo6.svg';
export {default as logo7} from './logo7.svg';
export {default as logo8} from './logo8.svg';
export {default as logo9} from './logo9.svg';